name: cs236781-hw
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # common
  - ffmpeg # needed for gym video output
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - nodejs>=12.0
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-xdist
  - python=3.8.12
  - scikit-learn=1.1
  - scipy
  - swig # needed to compile box2d
  - tqdm
  - pip:
    - nbmerge
  # pytorch
  - pytorch
  - cudatoolkit
  - torchvision
  - torchtext

platforms:
  - linux-64
